version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  manager:
    build: ./manager
    depends_on:
      - redis

  worker1:
    build: ./worker
    depends_on:
      - redis

  worker2:
    build: ./worker
    depends_on:
      - redis
